services:
  postgres:
    image: postgres:16
    container_name: node_backend_questlog_postgres_lab22

    environment:
      POSTGRES_USER: questlog
      POSTGRES_PASSWORD: questlog
      POSTGRES_DB: questlog

    ports:
      - "5436:5432"

    volumes:
      - lab22-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U questlog -d questlog"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v3.5.5
    container_name: node_backend_questlog_prometheus_lab22

    ports:
      - "9090:9090"

    extra_hosts:
      - "host.docker.internal=host-gateway"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z
      - lab22-prometheus-data:/prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"

volumes:
  lab22-postgres-data: {}
  lab22-prometheus-data: {}