services:
  postgres:
    image: postgres:16
    container_name: node_backend_questlog_postgres_lab21

    environment:
      POSTGRES_USER: questlog
      POSTGRES_PASSWORD: questlog
      POSTGRES_DB: questlog

    ports:
      - "5435:5432"

    volumes:
      - lab21-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U questlog -d questlog"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  lab21-postgres-data: {}